### ISSUE TITLE
Kernel battery drain, any solution ?

### ISSUE THREAD

**Issue by kevin2008-01** [MediatekAndroidDevelopers/android_kernel_oukitel_k6000_plus#1]
Hi, i use M.A.D 8.0 for K6000 Plus, very good rom, but the kennel drain very fast the battery.

Greenefy or battery software no stop the drain.

![drain1](https://user-images.githubusercontent.com/34159692/36964409-d52a8d30-2056-11e8-9413-2dc388efbab6.png)

Any solution or update ?

Thank you

**Comment by DerTeufel** [comment]
There's going to be android 8.1 soon. Please wait for it and check again then.

**Comment by dragonpt** [comment]
Forward to @fire855  he loves this
